sudo: false
dist: trusty

language: go
go: 1.8

install:
  - go version
  - go get github.com/kardianos/govendor
  - govendor get -v github.com/gohugoio/hugo

script:
  - "$GOPATH/bin/hugo --verbose"

notifications:
  email:
    on_success: never
    on_failure: change

deploy:
  provider: pages
  local_dir: web
  repo: factopolis/factopolis.github.io
  fqdn: www.factopolis.com
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
