sudo: false
dist: trusty

language: go
go: 1.8

addons:
  apt:
    packages: yajl-tools

install:
  - go version
  - go env
  - go get -u -v github.com/kardianos/govendor
  - go get -u -v github.com/gohugoio/hugo
  - (cd $GOPATH/src/github.com/gohugoio/hugo && govendor sync && go install)

script:
  - $GOPATH/bin/hugo --verbose
  - find web/ -name '*.json' | while read json; do json_reformat -m < "$json" > "$json.min" && mv "$json.min" "$json"; done

notifications:
  email:
    on_success: never
    on_failure: change

deploy:
  provider: pages
  local_dir: web
  repo: factopolis/factopolis.github.io
  fqdn: www.factopolis.com
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
