languageCode = "en-us"
title = "LieDB"
baseurl = "https://liedb.github.io/"

[outputs]
page = [ "HTML", "JSON" ]

[params]
analytics = "UA-101930305-1"

[[params.navlinks]]
name = "Home"
url = ""

[[params.navlinks]]
name = "Claims"
url = "claim/"

[[params.navlinks]]
name = "People"
url = "person/"
