languageCode = "en-us"
title = "Factopolis"
baseurl = "/"
GoogleAnalytics = "UA-101930305-1"
publishDir = "web"
paginate = 25
theme = "factopolis"
enableGitInfo = true

[taxonomies]
    claim = "claims"
    theme = "themes"
    group = "groups"

# So we can build special JSON for Algolia alongside the normal JSON
[mediaTypes]
    [mediaTypes."application/prs.factopolis-algolia"]
    suffix = "algolia.json"

[outputFormats.Algolia]
    mediaType = "application/prs.factopolis-algolia"
    isPlainText = true

[outputs]
    page = [ "HTML", "JSON" ]
    section = [ "HTML", "JSON" ]
    home = [ "HTML", "JSON", "RSS", "Algolia" ]
    taxonomy = [ "HTML", "JSON" ]
    taxonomyTerm = [ "HTML", "JSON" ]

[blackfriday]
    fractions = false

[params]
# Whether to enable Dart front-end (unfinished). This will become the
# default once the Dart front-end reaches parity.
Dart = false
