languageCode = "en-us"
title = "Factopolis"
baseurl = "http://www.factopolis.com/"

theme = "factopolis"

[outputs]
page = [ "HTML", "JSON" ]

[params]
analytics = "UA-101930305-1"

[[params.navlinks]]
name = "Factopolis"
url = ""

[[params.navlinks]]
name = "Claims"
url = "claim/"

[[params.navlinks]]
name = "People"
url = "person/"
