languageCode = "en-us"
title = "Factopolis"
baseurl = "/"
GoogleAnalytics = "UA-101930305-1"
publishDir = "web"

paginate = 25

theme = "factopolis"

[outputs]
page = [ "HTML", "JSON" ]
section = [ "HTML", "JSON" ]

[params]
# Whether to enable Dart front-end (unfinished). This will become the
# default once the Dart front-end reaches parity.
Dart = false
