languageCode = "en-us"
title = "Factopolis"
baseurl = "/"

theme = "factopolis"

[outputs]
page = [ "HTML", "JSON" ]

[params]
analytics = "UA-101930305-1"

[[params.navlinks]]
name = "Claims"
url = "claim/"

[[params.navlinks]]
name = "People"
url = "person/"

[[params.navlinks]]
name = "Groups"
url = "group/"
