languageCode = "en-us"
title = "Factopolis"
baseurl = "/"
GoogleAnalytics = "UA-101930305-1"

paginate = 25

theme = "factopolis"

[outputs]
page = [ "HTML", "JSON" ]

[[params.navlinks]]
name = "Claims"
url = "claim/"

[[params.navlinks]]
name = "People"
url = "person/"

[[params.navlinks]]
name = "Groups"
url = "group/"
